In [57]:
import numpy as np


class Soils:
    
    def __init__(self, path = "./Data/soils/suelos_risaralda_v2.csv"):
        
        
        self.path = path
        
        # Reading file
        records_matrix = open(self.path)
        # Reading the data 
        tmpMatriceData =  [l.strip().split(';') for l in records_matrix.readlines()[1::]]
        records_matrix.seek(0)
        tmpMatriceInfo =  [l.strip().split(';') for l in records_matrix.readlines()[:1]]
        self.matriceData = np.array(tmpMatriceData)
        self.matriceInfo = np.array(tmpMatriceInfo)
    
    # id   code      profile    layer   layer code
    #     _________ _________ _________ _________
    #  1 |  abc    |  abcP1  |        1|     abc1|
    #  2 |  abc    |  abcP1  |        2|     abc2|
    #  3 |  abc    |  abcP1  |        3|     abc3|
    #    |         |_________|_________|_________|
    #  4 |  abc    |  abcP2  |        1|     abc1|
    #  5 |  abc    |  abcP2  |        2|     abc2|
    #  6 |  abc    |  abcP2  |        3|     abc3|
    #  
    #  To get an unique identifier we need profile + layer code
    #  As we do to get pH or Organic 
    #
    
    
    def isNA(self, value):
        return (value == "NA" or value == "N.A." or value == "na" or value == "n.a.")
    
    # returns all ID's
    def getIds(self):
        array = [int(stridx)-1 for stridx in self.matriceData[:,0]]
        return array
    
    # returns all codes
    def getCodes(self):
        return self.matriceData[:,1]
    
    def getProfilCodes(self):
        return self.matriceData[:,2]
    
    # simply count the number of occurence of "profile" ex test value: 66MALP02
    def getNumberOfLayers(self,profile):
        count = 0
        for i in range(0,len(self.matriceData)):
            if self.matriceData[i,2] == profile:
                count += 1
        return count
    
    # return table with layers codes
    def getLayers(self, profile):
        layers = []
        
        for i in range(0, len(self.matriceData)):
            if self.matriceData[i,2] == profile:
                layers.append(self.matriceData[i,4])
        
        return layers
        
    
    # return id (1-70) => (0-69)
    # params: 
    def getLayerID(self, profile, layerCode):
        profileData = []
        
        for i in range(0, len(self.matriceData)):
            if self.matriceData[i,2] == profile:
                profileData.append(self.matriceData[i,:])
        profileData = np.array(profileData)
        
        for j in range(0, len(profileData)):
            if profileData[j, 4] == layerCode:
                return (int(profileData[j,0])) -1
        return None
    
    
    
    # returns the Horizon Symbol
    def getHorizonSymbol(self, layerID):
        
        return self.matriceData[layerID, 5]
    
    
    # returns the horizon depth informations (Start depth, Finish depth, depth)
    def getHorizonDepthInfos(self, layerID):
        
        return (self.matriceData[layerID, 6],self.matriceData[layerID, 7],self.matriceData[layerID, 8])

    
    # returns the textures table (5 binairy variable table)
    # Franco|Acrilloso|Limoso|Arenoso|Cascajoso
    def getTexture(self, layerID):
        
        textureValues = ["franco","arcilloso","limoso","arenoso","cascajoso"]
        
        
        textureTable = np.zeros(len(textureValues))
        
        data = self.matriceData[layerID, 9].lower()

        print data
        print layerID
        if self.isNA(data):
            print "No value - NA"
            return None
        
        
        for i in range(0, len(textureValues)):
            if textureValues[i] in data:
                textureTable[i] = 1
            if i == 1:
                # if contains acrillo 
                if "arcillo" in data:
                    textureTable[i] = 1
        
        
        return textureTable
    
    # returns the pH of the layer passed in parameter (float)
    def getPH(self, layerID):
        value = self.matriceData[layerID, 12]
        if(not self.isNA(value)):
            return float(value)
        else: 
            return None
    
    # returns the % of organic mater (float, percentage -> 0.8 means 0.8%)
    def getOrganic(self, layerID):
        value = self.matriceData[layerID, 13].replace('%','')
        if(not self.isNA(value)):
            return float(value)
        else:
            return None
    
    
    def getGravimetricHumidity1(self, layerID):
        value = self.matriceData[layerID, 14]
        if(not self.isNA(value)):
            return float(value)
        else:
            return None
    
    
    def getGravimetricHumidity2(self, layerID):
        value = self.matriceData[layerID, 15]
        if (not self.isNA(value)):
            return float(value)
        else: 
            return None
    
    
    def getUsableHumidity(self, layerID):
        
        value = self.matriceData[layerID, 16]
        if (not self.isNA(value)):
            return float(value)
        else: 
            return None
    
    
    def getRealDensity(self, layerID):
        
        value = self.matriceData[layerID, 17]
        if (not self.isNA(value)):
            return float(value)
        else: 
            return None
    
    
    def getApparentDensity(self, layerID):
        
        value = self.matriceData[layerID, 18]
        if (not self.isNA(value)):
            return float(value)
        else: 
            return None
    
    
    def getTotalPorosity(self, layerID):
        
        value = self.matriceData[layerID, 19]
        if (not self.isNA(value)):
            return float(value)
        else: 
            return None
    
    
    def layerSummary(self, layerID):
        summary = []
        summary.append(self.getPH(layerID))
        summary.append(self.getOrganic(layerID))
        summary.append(self.getHorizonSymbol(layerID))
        summary.append(self.getHorizonDepthInfos(layerID))
        summary.append(self.getGravimetricHumidity1(layerID))
        summary.append(self.getGravimetricHumidity2(layerID))
        summary.append(self.getUsableHumidity(layerID))
        summary.append(self.getRealDensity(layerID))
        summary.append(self.getApparentDensity(layerID))
        summary.append(self.getTotalPorosity(layerID))
        
        summary = np.array(summary)
        return summary
    


In [58]:
soilInfo = Soils()
#print soilInfo.matriceInfo
print soilInfo.getIds()
print soilInfo.matriceData[:,0]

#print soilInfo.getCodes()
#print soilInfo.getProfilCodes()

#print soilInfo.getLayers("66MALP02")

layerID = soilInfo.getLayerID("66MALP02", "66MAL3")
#print layerID
#print soilInfo.getPH(layerID)
#print soilInfo.getOrganic(layerID)
#print soilInfo.getHorizonSymbol(layerID)
#print soilInfo.getHorizonDepthInfos(layerID)
#print soilInfo.getGravimetricHumidity1(layerID)
#print soilInfo.getGravimetricHumidity2(layerID)
#print soilInfo.getUsableHumidity(layerID)
#print soilInfo.getRealDensity(layerID)
#print soilInfo.getApparentDensity(layerID)
#print soilInfo.getTotalPorosity(layerID)

#print soilInfo.layerSummary(layerID)
print soilInfo.getTexture(layerID)

for idx in soilInfo.getIds():
    print soilInfo.getTexture(idx)
    #print type(idx)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30' '31'
 '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44' '45' '46'
 '47' '48' '49' '50' '51' '52' '53' '54' '55' '56' '57' '58' '59' '60' '61'
 '62' '63' '64' '65' '66' '67' '68' '69' '70']
franco limoso
26
[ 1.  0.  1.  0.  0.]
arcilloso cascajoso
0
[ 0.  1.  0.  0.  1.]
arcilloso cascajoso
1
[ 0.  1.  0.  0.  1.]
franco limoso
2
[ 1.  0.  1.  0.  0.]
franco limoso
3
[ 1.  0.  1.  0.  0.]
franco arcillo-limoso
4
[ 1.  1.  1.  0.  0.]
arcilloso
5
[ 0.  1.  0.  0.  0.]
arcilloso
6
[ 0.  1.  0.  0.  0.]
arcilloso
7
[ 0.  1.  0.  0.  0.]
franco arcilloso cascajoso
8
[ 