# Ajout des données climatiques au dataset



In [1]:
import pandas as pd
import Averages as avgs

wrapper = avgs.ClimaticDataWraper(["2011","2012","2013","2014","2015","2016"])

Loading data for 2011
Done !
Loading data for 2012
Done !
Loading data for 2013
Done !
Loading data for 2014
Done !
Loading data for 2015
Done !
Loading data for 2016
Done !


In [2]:
df = pd.DataFrame.from_csv("./DataWithGPS_v1_utf-8.csv", header=0, sep=',', index_col=0, parse_dates=False, encoding='utf-8')
df

Cedula  Municipio        Vereda          Finca          SICA    CEDULA 1  \
0       NaN     Balboa    La Cienaga      Palestina  6.607501e+09    14257374   
1       NaN     Balboa    La Cienaga     La Albania  6.607501e+09     2280361   
2       NaN     Balboa    El Chuzcal   La Esperanza  6.607501e+09     4379287   
3       NaN     Balboa   Llanogrande       Altamira  6.607500e+09     4378752   
4       NaN     Balboa     Cocohondo       La Palma  6.607500e+09    65807427   
5       NaN     Balboa   La Floresta       La Paiva  6.607500e+09    42138525   
6       NaN     Balboa   Llanogrande       El Llano  6.607500e+09     4378773   
7       NaN     Balboa    Carminales  El Guadualito  6.607500e+09    30412314   
8       NaN     Balboa      Tambores      El Bosque  6.607501e+09     4551819   
9       NaN     Balboa   La Floresta      La Mejora  6.607501e+09    24512358   
10      NaN     Balboa   La Floresta       La Nubia  6.607500e+09     4522829   
11      NaN     Balboa    Carminales    La Estrella  6.607501e+09    10073917   
12      NaN     Balboa   San Antonio      El Reposo  6.607501e+09     4380259   
13      NaN     Balboa   San Antonio      El Reposo  6.607501e+09     4379758   
14      NaN   La Celia     Montblanc       El Truco  6.638301e+09    86000231   
15      NaN     Balboa    La Cienaga    El Lotecito  6.607500e+09     4379485   
16      NaN     Balboa    El Chuzcal     Las Brisas  6.607501e+09     4379258   
17      NaN     Balboa      Tambores    San Nicolas  6.607501e+09    16211928   
18      NaN     Balboa   Llanogrande      La Arabia  6.607500e+09    34041420   
19      NaN     Balboa   Llanogrande   El Banquillo  6.607500e+09    10119624   
20      NaN   La Celia  El Brillante    El Porvenir  6.638300e+09    42001965   
21      NaN   La Celia  El Brillante   La Esperanza  6.638301e+09    75147056   
22      NaN   La Celia     El Condor     La Perlita  6.638301e+09    16357498   
23      NaN   La Celia    La Cascada      La Granja  6.638301e+09    25201656   
24      NaN   La Celia      La Playa      El Regalo  6.638300e+09     3360475   
25      NaN   La Celia    La Polonia       Tesorito  6.638301e+09    18603648   
26      NaN   La Celia   La Zelandia     Cominalito  6.638300e+09    25201950   
27      NaN   La Celia   La Zelandia   Las Camelias  6.638300e+09    66884571   
28      NaN   La Celia   La Zelandia   El Brillante  6.638300e+09     9991855   
29      NaN   La Celia   La Zelandia        La Isla  6.638300e+09    16207122   
...     ...        ...           ...            ...           ...         ...   
1148    NaN   MARSELLA      LA LINDA            NaN  6.644001e+09     1309156   
1149    NaN   MARSELLA      LA LINDA            NaN  6.644002e+09    10132723   
1150    NaN   MARSELLA      LA LINDA            NaN  6.644001e+09    75085072   
1151    NaN   MARSELLA      LA LINDA            NaN  6.644001e+09  8908069375   
1152    NaN   MARSELLA   LA ORIENTAL            NaN  6.644001e+09     4556938   
1153    NaN   MARSELLA      LA PALMA            NaN  6.644002e+09    42136322   
1154    NaN   MARSELLA       LA POPA            NaN  6.644000e+09     4577971   
1155    NaN   MARSELLA       LA POPA            NaN  6.644000e+09    24763055   
1156    NaN   MARSELLA     LAS TAZAS            NaN  6.644001e+09  1088248578   
1157    NaN   MARSELLA     LAS TAZAS            NaN  6.644002e+09    42069045   
1158    NaN   MARSELLA     LAS TAZAS            NaN  6.644001e+09    71667937   
1159    NaN   MARSELLA     LAS TAZAS            NaN  6.644001e+09    10023496   
1160    NaN   MARSELLA     LAS TAZAS            NaN  6.644000e+09    10139867   
1161    NaN   MARSELLA     LAS TAZAS            NaN  6.644001e+09     4348763   
1162    NaN   MARSELLA     LAS TAZAS            NaN  6.644001e+09    17637543   
1163    NaN   MARSELLA   MANGABONITA            NaN  6.644001e+09    24762475   
1164    NaN   MARSELLA   MANGABONITA            NaN  6.644001e+09    24761741   
1165    NaN   MARSELLA   MIL OCHENTA

In [3]:
from datetime import *
#data_noNaN['Fecha Analysis'] = pd.to_datetime(data_noNaN['Fecha Analysis'])

for index, row in df.iterrows():
    try:
        date = datetime.strptime(row['Fecha Analysis'], '%m/%d/%Y %H:%M')
    except:
        date = datetime.strptime(row['Fecha Analysis'], '%m/%d/%Y')
    if date.year == 2017:
        date = date.replace(year = 2016)
    df.set_value(index,'Fecha Analysis', date)

# TODO Eliminate 2010


In [4]:
toDelete = []
for index, row in df.iterrows():
    if row['Fecha Analysis'].year == 2010 or (row['Fecha Analysis'].month < 11 and row['Fecha Analysis'].year == 2011):
        toDelete.append(index)
print toDelete

[38, 39, 40, 41, 42, 43, 44, 45, 46, 49, 436, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177]


In [5]:
df = df.drop(toDelete)
df = df.reset_index(drop=True)

In [6]:
df

Cedula  Municipio                 Vereda                   Finca  \
0            NaN     Balboa             La Cienaga               Palestina   
1            NaN     Balboa             La Cienaga              La Albania   
2            NaN     Balboa             El Chuzcal            La Esperanza   
3            NaN     Balboa            Llanogrande                Altamira   
4            NaN     Balboa              Cocohondo                La Palma   
5            NaN     Balboa            La Floresta                La Paiva   
6            NaN     Balboa            Llanogrande                El Llano   
7            NaN     Balboa             Carminales           El Guadualito   
8            NaN     Balboa               Tambores               El Bosque   
9            NaN     Balboa            La Floresta               La Mejora   
10           NaN     Balboa            La Floresta                La Nubia   
11           NaN     Balboa             Carminales             La Estrella   
12           NaN     Balboa            San Antonio               El Reposo   
13           NaN     Balboa            San Antonio               El Reposo   
14           NaN   La Celia              Montblanc                El Truco   
15           NaN     Balboa             La Cienaga             El Lotecito   
16           NaN     Balboa             El Chuzcal              Las Brisas   
17           NaN     Balboa               Tambores             San Nicolas   
18           NaN     Balboa            Llanogrande               La Arabia   
19           NaN     Balboa            Llanogrande            El Banquillo   
20           NaN   La Celia           El Brillante             El Porvenir   
21           NaN   La Celia           El Brillante            La Esperanza   
22           NaN   La Celia              El Condor              La Perlita   
23           NaN   La Celia             La Cascada               La Granja   
24           NaN   La Celia               La Playa               El Regalo   
25           NaN   La Celia             La Polonia                Tesorito   
26           NaN   La Celia            La Zelandia              Cominalito   
27           NaN   La Celia            La Zelandia            Las Camelias   
28           NaN   La Celia            La Zelandia            El Brillante   
29           NaN   La Celia            La Zelandia                 La Isla   
...          ...        ...                    ...                     ...   
1071    10005980        NaN              SABANITAS           VILLA MILENA    
1072     4453863        NaN          Manga Bonita              La Leticia    
1073    15900223        NaN  Campo Alegre Estacion          El Charrascal    
1074    79785341        NaN                Guacas          Finca del Café    
1075    18594512        NaN            La Florida              La Churria    
1076    18590733        NaN               El Chuzo            Las Melenas    
1077    15905284        NaN              El Chuzo               El Guayco    
1078     4587607        NaN               Barcinal              El Mirador   
1079  10,192,641        NaN         Bajo Esmeralda             Anda Lucia    
1080   4,589,886        NaN                Cominal             La Camelia    
1081     2255100        NaN            Santa Sofia           La Margarita    
1082     4587147        NaN           Alto Peñas B            La Herminia    
1083    25194333        NaN              La Union                Naranjal    
1084    18532432        NaN        Baja Esmeralda                 El Ruby    
1085    42027805        NaN              La Linda                 La Isla    
1086     4589156        NaN             El Yarumo           Pie de Cuesta    
1087    25191608        NaN          Buenos Aires   Luces de Buenos Aires    
1088     4349676        NaN              Oro Fino              La Miranda    
1089     8310724        NaN           Alto Peñas B               Alegrias    
1090     9957544        NaN     

In [7]:
# on va prendre les données climatiques pour 6 mois, jusqu'à 1 mois avant la dégustation 
import numpy as np
def getClimatDatas(x,y,year,monthDegust):
    
    
    
    precdata = wrapper.getPrecAverages([x,y])
    tmindata = wrapper.getTminAverages([x,y])
    tmaxdata = wrapper.getTmaxAverages([x,y])
    tmeandata = wrapper.getTmeanAverages([x,y])
    dtrdata = wrapper.getDtrAverages([x,y])
    
    # Si data 2010 - remplacer
    focus = year - 2011
    
    

    
    monthsidx = np.array([(month - 11),(month - 10),(month - 9),(month - 8),(month - 7),(month - 6),
                          (month - 5),(month - 4),(month - 3),(month - 2)])
    
    # idx of the month in the data returned by the wrapper (0 = jan)
    '''
        focus:          0               1               2               3               4               5
                |      2011     |      2012     |      2013     |      2014     |      2015     |      2016     | 
                |Jan - ... - dec|Jan - ... - dec|Jan - ... - dec|Jan - ... - dec|Jan - ... - dec|Jan - ... - dec|
                
        Exemple:        xxxxxx    
        
                    7 déc 2011 => focus = 0 
                    idxs = 0 * 12 + [5,6,7,8,9,10]
                
        
    
    '''
    
    
    idxs = monthsidx + (focus * 12)
    
    # for one position we have 5 tables of datas 
    #datastables = [precdata[idxs], tmindata[idxs], tmaxdata[idxs], tmeandata[idxs], dtrdata[idxs]]
    formated = []
    
    for val in precdata[idxs]: 
        formated.append(val)    
    for val in tmindata[idxs]: 
        formated.append(val)
    for val in tmaxdata[idxs]: 
        formated.append(val)
    for val in tmeandata[idxs]: 
        formated.append(val)
    for val in dtrdata[idxs]: 
        formated.append(val)
    print idxs
    
    return formated

# Receive all climatic data before beeing merged to the dataframe
tmpdatas = []

for index, row in df.iterrows():
    x = row['EPSG:3116_X']
    y = row['EPSG:3116_Y']
    year = row['Fecha Analysis'].year
    month = row['Fecha Analysis'].month
    tmpdatas.append(getClimatDatas(x,y,year,month))
#

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  

In [8]:
tmpdatas = np.array(tmpdatas)
print tmpdatas.shape

(1101L, 50L)


In [9]:
types = ['prec','tmin','tmax','tmean','dtr']
labels = []

for i in range(0,5):
    for j in range(0,10):
        labels.append(str(types[i])+str(j + 1))


print tmpdatas.shape
'''tmpdatas = tmpdatas.transpose()
print tmpdatas.shape'''



(1101L, 50L)


'tmpdatas = tmpdatas.transpose()\nprint tmpdatas.shape'

In [10]:

print df.shape
tmpdf = pd.DataFrame.from_records(tmpdatas, columns=labels)
print tmpdf.shape
print df.shape



(1101, 64)
(1101, 50)
(1101, 64)


In [11]:
df

Cedula  Municipio                 Vereda                   Finca  \
0            NaN     Balboa             La Cienaga               Palestina   
1            NaN     Balboa             La Cienaga              La Albania   
2            NaN     Balboa             El Chuzcal            La Esperanza   
3            NaN     Balboa            Llanogrande                Altamira   
4            NaN     Balboa              Cocohondo                La Palma   
5            NaN     Balboa            La Floresta                La Paiva   
6            NaN     Balboa            Llanogrande                El Llano   
7            NaN     Balboa             Carminales           El Guadualito   
8            NaN     Balboa               Tambores               El Bosque   
9            NaN     Balboa            La Floresta               La Mejora   
10           NaN     Balboa            La Floresta                La Nubia   
11           NaN     Balboa             Carminales             La Estrella   
12           NaN     Balboa            San Antonio               El Reposo   
13           NaN     Balboa            San Antonio               El Reposo   
14           NaN   La Celia              Montblanc                El Truco   
15           NaN     Balboa             La Cienaga             El Lotecito   
16           NaN     Balboa             El Chuzcal              Las Brisas   
17           NaN     Balboa               Tambores             San Nicolas   
18           NaN     Balboa            Llanogrande               La Arabia   
19           NaN     Balboa            Llanogrande            El Banquillo   
20           NaN   La Celia           El Brillante             El Porvenir   
21           NaN   La Celia           El Brillante            La Esperanza   
22           NaN   La Celia              El Condor              La Perlita   
23           NaN   La Celia             La Cascada               La Granja   
24           NaN   La Celia               La Playa               El Regalo   
25           NaN   La Celia             La Polonia                Tesorito   
26           NaN   La Celia            La Zelandia              Cominalito   
27           NaN   La Celia            La Zelandia            Las Camelias   
28           NaN   La Celia            La Zelandia            El Brillante   
29           NaN   La Celia            La Zelandia                 La Isla   
...          ...        ...                    ...                     ...   
1071    10005980        NaN              SABANITAS           VILLA MILENA    
1072     4453863        NaN          Manga Bonita              La Leticia    
1073    15900223        NaN  Campo Alegre Estacion          El Charrascal    
1074    79785341        NaN                Guacas          Finca del Café    
1075    18594512        NaN            La Florida              La Churria    
1076    18590733        NaN               El Chuzo            Las Melenas    
1077    15905284        NaN              El Chuzo               El Guayco    
1078     4587607        NaN               Barcinal              El Mirador   
1079  10,192,641        NaN         Bajo Esmeralda             Anda Lucia    
1080   4,589,886        NaN                Cominal             La Camelia    
1081     2255100        NaN            Santa Sofia           La Margarita    
1082     4587147        NaN           Alto Peñas B            La Herminia    
1083    25194333        NaN              La Union                Naranjal    
1084    18532432        NaN        Baja Esmeralda                 El Ruby    
1085    42027805        NaN              La Linda                 La Isla    
1086     4589156        NaN             El Yarumo           Pie de Cuesta    
1087    25191608        NaN          Buenos Aires   Luces de Buenos Aires    
1088     4349676        NaN              Oro Fino              La Miranda    
1089     8310724        NaN           Alto Peñas B               Alegrias    
1090     9957544        NaN     

In [12]:
tmpdf

prec1             prec2             prec3             prec4  \
0     145.655600585937  205.839479980469  257.519198608398  195.011119995117   
1     147.673640136719  193.916400146484  257.884317626953  197.673759155273   
2     138.982078857422  205.851759033203  242.809320068359  178.794560546875   
3     139.238720092773  205.736319580078  235.844479980469  178.932759399414   
4     135.702360839844  196.869079589844  225.344479370117  170.141558837891   
5     146.721480102539  200.230720214844  258.594281616211  196.977960205078   
6     146.140280151367  203.069520263672  257.035401000977  199.094400024414   
7     141.535239868164  208.818560791016  242.029041137695  182.528279418945   
8     143.263719482422    205.8933203125  254.750961303711   187.44880065918   
9     146.046480712891  204.142080688477  258.391840820312  195.522799072266   
10    146.046480712891  204.142080688477  258.391840820312  195.522799072266   
11    143.792721557617  211.221678466797  249.640199584961  188.628278808594   
12    144.566919555664  205.452919921875  256.560279541016  191.569799804688   
13    139.564120483398  205.553600463867  244.859000244141  178.131200561523   
14    144.448159790039   202.97291809082   254.59876159668  195.472720336914   
15    147.470719604492  191.393318481445  256.590837402344  196.949801025391   
16    145.407881164551  182.909279785156  250.118119506836  192.075440673828   
17    141.160278320312  204.648800048828  251.479118652344  181.970161132813   
18    136.461759643555  199.846921386719  228.531040039063  172.537359619141   
19    144.628040161133  206.315399780273  254.776038818359  195.138280029297   
20    140.781638793945  178.762120361328  242.268159790039  188.916799316406   
21     137.53315826416  167.955200195312  234.145880737305  182.978039550781   
22    143.963718261719  191.722720336914  250.860841674805  196.022559814453   
23    141.698200683594   201.30416015625  250.962561645508  189.645958862305   
24    140.308439025879  183.309920654297  242.967958984375  190.463999023438   
25    141.416880493164  199.047758178711  249.280198974609  191.073200073242   
26    140.472359924316  187.471478881836  244.306161499023  190.449800415039   
27    138.840038757324  177.621598510742  239.037559814453  184.837521362305   
28     138.39359954834     176.223359375  237.985918579102  184.225842285156   
29     138.39359954834     176.223359375  237.985918579102  184.225842285156   
...                ...               ...               ...               ...   
1071  126.231480407715  103.660400085449  111.322600708008  196.795360717773   
1072  250.974680175781  216.995961303711  115.863159484863  91.6390802001953   
1073  124.741920166016  97.8725994873047  112.234360351563  208.578439941406   
1074  122.980960083008  106.186679992676  113.054119262695  207.994079589844   
1075  126.028520507813  100.938119812012  118.430520324707  208.467520141602   
1076   127.47004119873  102.958800048828  118.351119995117  208.803198852539   
1077    126.4299609375  104.585199890137   115.13716003418  201.325440063477   
1078  167.803159179687  112.501919555664  75.9948391723633  98.0455606079102   
1079  177.995640869141  126.037600402832  77.5883197021484  93.6808401489258   
1080  174.118760375977  121.848640136719  75.1487191772461  88.2713595581055   
1081  95.8608801269531  68.8162004089355  94.2700793457031  125.159638671875   
1082  118.249519958496  76.4482797241211  98.2599603271484  127.715639038086   
1083  119.351600341797  76.4247192382813  98.3224795532226  123.615520629883   
1084  126.198159484863  77.4099993896484   94.531559753418  109.671840057373   
1085  125.941880187988  76.7563995361328  93.3906402587891  108.632479553223   
1086  107.407959899902  77.1503598022461  100.114520263672  141.789760742187   
1087  121.900680847168  77.4644409179687  98.9965200805664  121.425639648437   
1088  125.662399291992  78.1345602416992  97.0544000244141  115.409400634766   
1089  118.7245602

In [13]:
dfresult = pd.concat([df, tmpdf], axis=1)
dfresult

Cedula  Municipio                 Vereda                   Finca  \
0            NaN     Balboa             La Cienaga               Palestina   
1            NaN     Balboa             La Cienaga              La Albania   
2            NaN     Balboa             El Chuzcal            La Esperanza   
3            NaN     Balboa            Llanogrande                Altamira   
4            NaN     Balboa              Cocohondo                La Palma   
5            NaN     Balboa            La Floresta                La Paiva   
6            NaN     Balboa            Llanogrande                El Llano   
7            NaN     Balboa             Carminales           El Guadualito   
8            NaN     Balboa               Tambores               El Bosque   
9            NaN     Balboa            La Floresta               La Mejora   
10           NaN     Balboa            La Floresta                La Nubia   
11           NaN     Balboa             Carminales             La Estrella   
12           NaN     Balboa            San Antonio               El Reposo   
13           NaN     Balboa            San Antonio               El Reposo   
14           NaN   La Celia              Montblanc                El Truco   
15           NaN     Balboa             La Cienaga             El Lotecito   
16           NaN     Balboa             El Chuzcal              Las Brisas   
17           NaN     Balboa               Tambores             San Nicolas   
18           NaN     Balboa            Llanogrande               La Arabia   
19           NaN     Balboa            Llanogrande            El Banquillo   
20           NaN   La Celia           El Brillante             El Porvenir   
21           NaN   La Celia           El Brillante            La Esperanza   
22           NaN   La Celia              El Condor              La Perlita   
23           NaN   La Celia             La Cascada               La Granja   
24           NaN   La Celia               La Playa               El Regalo   
25           NaN   La Celia             La Polonia                Tesorito   
26           NaN   La Celia            La Zelandia              Cominalito   
27           NaN   La Celia            La Zelandia            Las Camelias   
28           NaN   La Celia            La Zelandia            El Brillante   
29           NaN   La Celia            La Zelandia                 La Isla   
...          ...        ...                    ...                     ...   
1071    10005980        NaN              SABANITAS           VILLA MILENA    
1072     4453863        NaN          Manga Bonita              La Leticia    
1073    15900223        NaN  Campo Alegre Estacion          El Charrascal    
1074    79785341        NaN                Guacas          Finca del Café    
1075    18594512        NaN            La Florida              La Churria    
1076    18590733        NaN               El Chuzo            Las Melenas    
1077    15905284        NaN              El Chuzo               El Guayco    
1078     4587607        NaN               Barcinal              El Mirador   
1079  10,192,641        NaN         Bajo Esmeralda             Anda Lucia    
1080   4,589,886        NaN                Cominal             La Camelia    
1081     2255100        NaN            Santa Sofia           La Margarita    
1082     4587147        NaN           Alto Peñas B            La Herminia    
1083    25194333        NaN              La Union                Naranjal    
1084    18532432        NaN        Baja Esmeralda                 El Ruby    
1085    42027805        NaN              La Linda                 La Isla    
1086     4589156        NaN             El Yarumo           Pie de Cuesta    
1087    25191608        NaN          Buenos Aires   Luces de Buenos Aires    
1088     4349676        NaN              Oro Fino              La Miranda    
1089     8310724        NaN           Alto Peñas B               Alegrias    
1090     9957544        NaN     

In [14]:
dfresult.to_csv("DataWithClimat_v1_utf-8.csv", sep=',', encoding='utf-8')
dfresult.to_csv("DataWithClimat_v1_iso-8859-1.csv", sep=',', encoding='iso-8859-1')